force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>S-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending for 1st Level Approval</fullName>
            </value>
            <value>
                <fullName>Pending for 2nd Level Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In - Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BranchTriggerTest.cls
@isTest
public class BranchTriggerTest{
    @IsTest
    static void insertMethod(){
        Student__c br = new Student__c();
        br.Name__c = 'test branch';
        br.Status__c = 'New';

        test.startTest();
        insert br;
        test.stopTest();

        System.assert(br.Id != null);
        system.assertEquals('test project', br.Name__c);
    }


    @IsTest
    static void updateMethod1(){
        Student__c br = new Student__c();
        br.Name__c = 'test branch';
        br.Status__c = 'New';
        insert br;

        test.startTest();
        br.Status__c = 'In Progress';
        update br;
        test.stopTest();

        System.assert(br.Id != null);
        system.assertEquals('test project', br.Name__c);

    }
}