force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>B-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In - Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>S-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Branch_Name__c.field-meta.xml
<CustomField>
    <fullName>Branch_Name__c</fullName>
    <formula>Branch_Parent_ID__r.Branch_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Branch Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Student__c/fields/Branch_Parent_ID__c.field-meta.xml
<CustomField>
    <fullName>Branch_Parent_ID__c</fullName>
    <label>Branch Parent ID</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending for 1st Level Approval</fullName>
            </value>
            <value>
                <fullName>Pending for 2nd Level Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In - Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BranchTriggerHandlerTest.cls
@isTest
public  class BranchTriggerHandlerTest {
    @isTest
    static void testProjectInsert(){
        Branch__c br = new Branch__c();
        br.Branch_Name__c = 'test branch';
        br.Status__c = 'New';
        insert br;

        List<Branch__c> brList = new List<Branch__c>();
        brList.add(br);
        test.startTest();

        //test insert ticket method
        BranchTriggerHandler.createDefaultBranch(brList);
        test.stopTest();

        Student__c insertStudent = [select id,Name__c,Phone__c from Student__c limit 1 ];
        system.assert(insertStudent!= null);
        System.assertEquals('324739434', insertStudent.Phone__c);

    }
    @isTest
    static void testProjectUpdateCheckError(){
        Branch__c br = new Branch__c();
        br.Branch_Name__c = 'test branch';
        br.Status__c = 'New';
        insert br;

        //insert branch name
        Student__c st = new Student__c();
        st.Name__c = 'Test';
        st.Branch_Parent_ID__c = br.id;
        insert st;

        //update project status
        Test.startTest();
        try{
            br.Status__c = 'Completed';
            update br;
        }catch(Exception ex){
            system.assert(ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION'));
        }
        Test.stopTest();
    }

 @istest
    static void testProjectUpdateDescriptionFuture() {
       Branch__c sp = new Branch__c();
        sp.Branch_Name__c = 'test project';
        sp.Status__c = 'New';
        insert sp;
        

        //update project status
        Test.startTest();
       BranchTriggerHandler.updateBranchDescriptionFuture(new set<id>{sp.id});
        Test.stopTest();

        List<Branch__c> spList = [select id, name, description__c from Branch__c];
        System.assert(spList != null);
        system.assert(spList.get(0).Description__c.contains('Future'));
    }
}