force-app/main/default/objects/Branch__c/Branch__c.object-meta.xml
<CustomObject>
    <label>Branch</label>
    <nameField>
        <displayFormat>B-{000}</displayFormat>
        <label>B-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Branches</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Branch__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
                <default>true</default>
                <label>New</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In - Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <label>Student</label>
    <nameField>
        <displayFormat>S-{000}</displayFormat>
        <label>S-ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Student__c/fields/Branch_Parent_ID__c.field-meta.xml
<CustomField>
    <fullName>Branch_Parent_ID__c</fullName>
    <label>Branch Parent ID</label>
    <referenceTo>Branch__c</referenceTo>
    <relationshipLabel>Students</relationshipLabel>
    <relationshipName>Students</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
    <writeRequiresMasterRead>true</writeRequiresMasterRead>
</CustomField>

force-app/main/default/objects/Student__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Pending for 1st Level Approval</fullName>
            </value>
            <value>
                <fullName>Pending for 2nd Level Approval</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>In - Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BranchTriggerHandler.cls
public with sharing class BranchTriggerHandler{

//update description in future method.....

@future
public static void updateBranchDescriptionFuture(Set<Id> setBrId){
  System.debug('Future method called ');

  List<Branch__c> lstBr = [select id, name, Description__c from Branch__c where id in : setBrId];

  //update description in for each loop
for(Branch__c eachbr: lstBr){
  eachbr.Description__c = eachbr.Description__c + '- Future method called';

}
update lstBr;
 }


 /*Q-If we call this future Method --> updateBranchDescriptionFuture 
 from AfterUpdate it will failed. Why? Because you cannot call the Future method
 from the future method. How to resolve the ERROR*/











 

  public static void createDefaultBranch(List<Branch__c> branchTriggerNew){
    //create one empty List of Student
    List<Student__c> newStudentList = new List<Student__c>();

    //for each branch create new Student
    for (Branch__c eachBranch : branchTriggerNew){

      //create new instance
      Student__c students = new Student__c();
      students.Phone__c = '324739434';
      students.Name__c = eachBranch.Name;
      students.Branch_Parent_ID__c = eachBranch.id; //M/D relationship field ---> Branch_Parent_ID__c
      newStudentList.add(students);

    }
    insert newStudentList;
  }




  public static void validateBranchCompletion(List<Branch__c> brTriggerNew, Map<id, Branch__c> brTriggerNewMap, Map<id, Branch__c> brTriggerOldMap){

    //Find All Branch witch are Completed
    set<id> setCompletedBranchid = new set<Id>();
    /* B1 - Updated Name --But here the status is already completd
      B2 - Made status to completed-->
      B3 - Made staus to in-progress
    */
    //Identify whether the status has been changed or not and if its is changes new value is completed or not
    for (Branch__c eachBranch : brTriggerNew){
      if (brTriggerOldMap.get(eachBranch.Id).Status__c != brTriggerNewMap.get(eachBranch.Id).Status__c && eachBranch.Status__c == 'Completed'){
        setCompletedBranchid.add(eachBranch.Id);
      }
      /*if(eachBranch.Status__c == 'Completed' && brTriggerOldMap.get(eachBranch.Id).Status__c != 'Completed'){

      }*/

    }

    List<Student__c> studentList = [select id, name, Status__c, Branch_Parent_ID__c
                                from Student__c
                                where Branch_Parent_ID__c in :setCompletedBranchid and Status__c != 'Completed'];

    for (Student__c eachStudent : studentList){
      if (setCompletedBranchid.contains(eachStudent.Branch_Parent_ID__c)){ //relationship fields


        Branch__c brch = brTriggerNewMap.get(eachStudent.Branch_Parent_ID__c);
        brch.addError('Cannot Complete branch because all its Students are not completed.');
      }

    }
  }
}